heat_template_version: 2013-05-23

description: >
  Attach the network policy to two virtual networks

parameters:
  policy_name:
    type: string
    description: Virtual network id
  net_1_name:
    type: string
    description: Name of network to be created
  tenant_name:
    type: string
    description: Tenant name

resources:
  policy_attach_net1:
    type: OS::Contrail::AttachPolicyDA
    properties:
      network: { get_param: net_1_name }
      policy:  { get_param: policy_name }
      tenant:  { get_param: tenant_name }

