heat_template_version: 2013-05-23

description: >
  HOT template to creates a virtual network, subnet

parameters:
  net_name:
    type: string
    description: Name of virtual network to be created
  shared:
    type: string
    description: Is virtual network shared
    default: False
  external:
    type: string
    description: Is virtual network external
    default: False
#  forwarding_mode:
#    type: string
#    description: forwarding mode of the virtual network, allowed: l2_l3, l2
#  flood_unknown_unicast:
#    type: string
#    description: flood L2 packets on network
#  allow_transit:
#    type: string
#    description: Whether this network should be transitive.
  ip_prefix:
    type: string
    description: The CIDR
  default_gateway:
    type: string
    description: The default gateway
  dhcp:
    type: string
    description: Enable DHCP (True or False)
    default: True
  dns_nameservers:
    description: DNS Nameservers list
    type: comma_delimited_list
    default: 8.8.8.8
  route_targets:
    description: RT list
    type: comma_delimited_list
    default: []

resources:
  virtual_network:
    type: OS::Contrail::VirtualNetwork
    properties:
      name:                  { get_param: net_name }
      shared:                { get_param: shared }
      external:              { get_param: external }
      route_targets:         { get_param: route_targets }
#      route_targets:         { "Fn::Split" : [ ",", Ref: route_targets ] }
#      forwarding_mode:       { get_param: forwarding_mode }
#      flood_unknown_unicast: { get_param: flood_unknown_unicast }
#      allow_transit:         { get_param: allow_transit }

  virtual_subnet:
    type: OS::Contrail::VnSubnet
    depends_on: virtual_network
    properties:
      network:         { get_resource: virtual_network }
      ip_prefix:       { get_param: ip_prefix }
      default_gateway: { get_param: default_gateway }
      enable_dhcp:     { get_param: dhcp }

#  server_port:
#    type: OS::Neutron::Port
#    depends_on: virtual_subnet
#    properties:
#      network: { get_resource: virtual_network }
